remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: light

title: bos311-civic-data-explorer
description: An automated pipeline and interactive dashboard tracking Boston's 311 service requests.


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

navigation:
  - name: Read Me
    link: ./README.md
  - name: Executive Summary
    link: ./executive-summary
  - name: Dashboard
    link: ./dashboard
  - name: Ingest Script
    link: ./pipeline/ingest_311
